/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArcanumLayout: typeof import('./components/ArcanumLayout.vue')['default']
    CommentNode: typeof import('./components/CommentNode.vue')['default']
    HelpChat: typeof import('./components/HelpChat.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    README: typeof import('./components/README.md')['default']
    RichCommentEditor: typeof import('./components/RichCommentEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
